[tools]
erlang = "28"
gleam = "1.14"
rebar = "3.25.1"

[env]
CHROBOT_BROWSER_ARGS = """
--headless
--disable-accelerated-2d-canvas
--disable-gpu
--allow-pre-commit-input
--disable-background-networking
--disable-background-timer-throttling
--disable-backgrounding-occluded-windows
--disable-breakpad
--disable-client-side-phishing-detection
--disable-component-extensions-with-background-pages
--disable-component-update
--disable-default-apps
--disable-extensions
--disable-features=Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints
--disable-hang-monitor
--disable-ipc-flooding-protection
--disable-popup-blocking
--disable-prompt-on-repost
--disable-renderer-backgrounding
--disable-sync
--enable-automation
--enable-features=NetworkServiceInProcess2
--export-tagged-pdf
--force-color-profile=srgb
--hide-scrollbars
--metrics-recording-only
--no-default-browser-check
--no-first-run
--no-service-autorun
--password-store=basic
--use-mock-keychain
--no-sandbox
--disable-dev-shm-usage
--disable-setuid-sandbox
"""

[tasks.codegen]
run = "./codegen.sh"
