//// > ⚙️  This module was generated from the Chrome DevTools Protocol version **1.3**
//// ## Runtime Domain  
////
//// Runtime domain exposes JavaScript runtime by means of remote evaluation and mirror objects.
//// Evaluation results are returned as mirror object that expose object type, string representation
//// and unique identifier that can be used for further object reference. Original objects are
//// maintained in memory unless they are either explicitly released or are released along with the
//// other objects in their object group.  
////
//// [📖   View this domain on the DevTools Protocol API Docs](https://chromedevtools.github.io/devtools-protocol/1-3/Runtime/)

// ---------------------------------------------------------------------------
// |  !!!!!!   This is an autogenerated file - Do not edit manually  !!!!!!  |
// | Run ` gleam run -m scripts/generate_protocol_bindings.sh` to regenerate.|  
// ---------------------------------------------------------------------------

import chrome
import gleam/dict
import gleam/dynamic
import gleam/option

/// Unique script identifier.
pub type ScriptId {
  ScriptId(String)
}

/// Represents options for serialization. Overrides `generatePreview` and `returnByValue`.
pub type SerializationOptions {
  SerializationOptions(
    serialization: SerializationOptionsSerialization,
    max_depth: option.Option(Int),
    additional_parameters: option.Option(dict.Dict(String, String)),
  )
}

/// This type is not part of the protocol spec, it has been generated dynamically 
/// to represent the possible values of the enum property `serialization` of `SerializationOptions`
pub type SerializationOptionsSerialization {
  SerializationOptionsSerializationDeep
  SerializationOptionsSerializationJson
  SerializationOptionsSerializationIdOnly
}

@internal
pub fn encode__serialization_options_serialization(value: SerializationOptionsSerialization) {
  case value {
    SerializationOptionsSerializationDeep -> "deep"
    SerializationOptionsSerializationJson -> "json"
    SerializationOptionsSerializationIdOnly -> "idOnly"
  }
}

@internal
pub fn decode__serialization_options_serialization(value: String) {
  case value {
    "deep" -> Ok(SerializationOptionsSerializationDeep)
    "json" -> Ok(SerializationOptionsSerializationJson)
    "idOnly" -> Ok(SerializationOptionsSerializationIdOnly)
    _ -> Error(chrome.ProtocolError)
  }
}

/// Represents deep serialized value.
pub type DeepSerializedValue {
  DeepSerializedValue(
    type_: DeepSerializedValueType,
    value: option.Option(dynamic.Dynamic),
    object_id: option.Option(String),
    weak_local_object_reference: option.Option(Int),
  )
}

/// This type is not part of the protocol spec, it has been generated dynamically 
/// to represent the possible values of the enum property `type` of `DeepSerializedValue`
pub type DeepSerializedValueType {
  DeepSerializedValueTypeUndefined
  DeepSerializedValueTypeNull
  DeepSerializedValueTypeString
  DeepSerializedValueTypeNumber
  DeepSerializedValueTypeBoolean
  DeepSerializedValueTypeBigint
  DeepSerializedValueTypeRegexp
  DeepSerializedValueTypeDate
  DeepSerializedValueTypeSymbol
  DeepSerializedValueTypeArray
  DeepSerializedValueTypeObject
  DeepSerializedValueTypeFunction
  DeepSerializedValueTypeMap
  DeepSerializedValueTypeSet
  DeepSerializedValueTypeWeakmap
  DeepSerializedValueTypeWeakset
  DeepSerializedValueTypeError
  DeepSerializedValueTypeProxy
  DeepSerializedValueTypePromise
  DeepSerializedValueTypeTypedarray
  DeepSerializedValueTypeArraybuffer
  DeepSerializedValueTypeNode
  DeepSerializedValueTypeWindow
  DeepSerializedValueTypeGenerator
}

@internal
pub fn encode__deep_serialized_value_type(value: DeepSerializedValueType) {
  case value {
    DeepSerializedValueTypeUndefined -> "undefined"
    DeepSerializedValueTypeNull -> "null"
    DeepSerializedValueTypeString -> "string"
    DeepSerializedValueTypeNumber -> "number"
    DeepSerializedValueTypeBoolean -> "boolean"
    DeepSerializedValueTypeBigint -> "bigint"
    DeepSerializedValueTypeRegexp -> "regexp"
    DeepSerializedValueTypeDate -> "date"
    DeepSerializedValueTypeSymbol -> "symbol"
    DeepSerializedValueTypeArray -> "array"
    DeepSerializedValueTypeObject -> "object"
    DeepSerializedValueTypeFunction -> "function"
    DeepSerializedValueTypeMap -> "map"
    DeepSerializedValueTypeSet -> "set"
    DeepSerializedValueTypeWeakmap -> "weakmap"
    DeepSerializedValueTypeWeakset -> "weakset"
    DeepSerializedValueTypeError -> "error"
    DeepSerializedValueTypeProxy -> "proxy"
    DeepSerializedValueTypePromise -> "promise"
    DeepSerializedValueTypeTypedarray -> "typedarray"
    DeepSerializedValueTypeArraybuffer -> "arraybuffer"
    DeepSerializedValueTypeNode -> "node"
    DeepSerializedValueTypeWindow -> "window"
    DeepSerializedValueTypeGenerator -> "generator"
  }
}

@internal
pub fn decode__deep_serialized_value_type(value: String) {
  case value {
    "undefined" -> Ok(DeepSerializedValueTypeUndefined)
    "null" -> Ok(DeepSerializedValueTypeNull)
    "string" -> Ok(DeepSerializedValueTypeString)
    "number" -> Ok(DeepSerializedValueTypeNumber)
    "boolean" -> Ok(DeepSerializedValueTypeBoolean)
    "bigint" -> Ok(DeepSerializedValueTypeBigint)
    "regexp" -> Ok(DeepSerializedValueTypeRegexp)
    "date" -> Ok(DeepSerializedValueTypeDate)
    "symbol" -> Ok(DeepSerializedValueTypeSymbol)
    "array" -> Ok(DeepSerializedValueTypeArray)
    "object" -> Ok(DeepSerializedValueTypeObject)
    "function" -> Ok(DeepSerializedValueTypeFunction)
    "map" -> Ok(DeepSerializedValueTypeMap)
    "set" -> Ok(DeepSerializedValueTypeSet)
    "weakmap" -> Ok(DeepSerializedValueTypeWeakmap)
    "weakset" -> Ok(DeepSerializedValueTypeWeakset)
    "error" -> Ok(DeepSerializedValueTypeError)
    "proxy" -> Ok(DeepSerializedValueTypeProxy)
    "promise" -> Ok(DeepSerializedValueTypePromise)
    "typedarray" -> Ok(DeepSerializedValueTypeTypedarray)
    "arraybuffer" -> Ok(DeepSerializedValueTypeArraybuffer)
    "node" -> Ok(DeepSerializedValueTypeNode)
    "window" -> Ok(DeepSerializedValueTypeWindow)
    "generator" -> Ok(DeepSerializedValueTypeGenerator)
    _ -> Error(chrome.ProtocolError)
  }
}

/// Unique object identifier.
pub type RemoteObjectId {
  RemoteObjectId(String)
}

/// Primitive value which cannot be JSON-stringified. Includes values `-0`, `NaN`, `Infinity`,
/// `-Infinity`, and bigint literals.
pub type UnserializableValue {
  UnserializableValue(String)
}

/// Mirror object referencing original JavaScript object.
pub type RemoteObject {
  RemoteObject(
    type_: RemoteObjectType,
    subtype: option.Option(RemoteObjectSubtype),
    class_name: option.Option(String),
    value: option.Option(dynamic.Dynamic),
    unserializable_value: option.Option(UnserializableValue),
    description: option.Option(String),
    object_id: option.Option(RemoteObjectId),
  )
}

/// This type is not part of the protocol spec, it has been generated dynamically 
/// to represent the possible values of the enum property `type` of `RemoteObject`
pub type RemoteObjectType {
  RemoteObjectTypeObject
  RemoteObjectTypeFunction
  RemoteObjectTypeUndefined
  RemoteObjectTypeString
  RemoteObjectTypeNumber
  RemoteObjectTypeBoolean
  RemoteObjectTypeSymbol
  RemoteObjectTypeBigint
}

@internal
pub fn encode__remote_object_type(value: RemoteObjectType) {
  case value {
    RemoteObjectTypeObject -> "object"
    RemoteObjectTypeFunction -> "function"
    RemoteObjectTypeUndefined -> "undefined"
    RemoteObjectTypeString -> "string"
    RemoteObjectTypeNumber -> "number"
    RemoteObjectTypeBoolean -> "boolean"
    RemoteObjectTypeSymbol -> "symbol"
    RemoteObjectTypeBigint -> "bigint"
  }
}

@internal
pub fn decode__remote_object_type(value: String) {
  case value {
    "object" -> Ok(RemoteObjectTypeObject)
    "function" -> Ok(RemoteObjectTypeFunction)
    "undefined" -> Ok(RemoteObjectTypeUndefined)
    "string" -> Ok(RemoteObjectTypeString)
    "number" -> Ok(RemoteObjectTypeNumber)
    "boolean" -> Ok(RemoteObjectTypeBoolean)
    "symbol" -> Ok(RemoteObjectTypeSymbol)
    "bigint" -> Ok(RemoteObjectTypeBigint)
    _ -> Error(chrome.ProtocolError)
  }
}

/// This type is not part of the protocol spec, it has been generated dynamically 
/// to represent the possible values of the enum property `subtype` of `RemoteObject`
pub type RemoteObjectSubtype {
  RemoteObjectSubtypeArray
  RemoteObjectSubtypeNull
  RemoteObjectSubtypeNode
  RemoteObjectSubtypeRegexp
  RemoteObjectSubtypeDate
  RemoteObjectSubtypeMap
  RemoteObjectSubtypeSet
  RemoteObjectSubtypeWeakmap
  RemoteObjectSubtypeWeakset
  RemoteObjectSubtypeIterator
  RemoteObjectSubtypeGenerator
  RemoteObjectSubtypeError
  RemoteObjectSubtypeProxy
  RemoteObjectSubtypePromise
  RemoteObjectSubtypeTypedarray
  RemoteObjectSubtypeArraybuffer
  RemoteObjectSubtypeDataview
  RemoteObjectSubtypeWebassemblymemory
  RemoteObjectSubtypeWasmvalue
}

@internal
pub fn encode__remote_object_subtype(value: RemoteObjectSubtype) {
  case value {
    RemoteObjectSubtypeArray -> "array"
    RemoteObjectSubtypeNull -> "null"
    RemoteObjectSubtypeNode -> "node"
    RemoteObjectSubtypeRegexp -> "regexp"
    RemoteObjectSubtypeDate -> "date"
    RemoteObjectSubtypeMap -> "map"
    RemoteObjectSubtypeSet -> "set"
    RemoteObjectSubtypeWeakmap -> "weakmap"
    RemoteObjectSubtypeWeakset -> "weakset"
    RemoteObjectSubtypeIterator -> "iterator"
    RemoteObjectSubtypeGenerator -> "generator"
    RemoteObjectSubtypeError -> "error"
    RemoteObjectSubtypeProxy -> "proxy"
    RemoteObjectSubtypePromise -> "promise"
    RemoteObjectSubtypeTypedarray -> "typedarray"
    RemoteObjectSubtypeArraybuffer -> "arraybuffer"
    RemoteObjectSubtypeDataview -> "dataview"
    RemoteObjectSubtypeWebassemblymemory -> "webassemblymemory"
    RemoteObjectSubtypeWasmvalue -> "wasmvalue"
  }
}

@internal
pub fn decode__remote_object_subtype(value: String) {
  case value {
    "array" -> Ok(RemoteObjectSubtypeArray)
    "null" -> Ok(RemoteObjectSubtypeNull)
    "node" -> Ok(RemoteObjectSubtypeNode)
    "regexp" -> Ok(RemoteObjectSubtypeRegexp)
    "date" -> Ok(RemoteObjectSubtypeDate)
    "map" -> Ok(RemoteObjectSubtypeMap)
    "set" -> Ok(RemoteObjectSubtypeSet)
    "weakmap" -> Ok(RemoteObjectSubtypeWeakmap)
    "weakset" -> Ok(RemoteObjectSubtypeWeakset)
    "iterator" -> Ok(RemoteObjectSubtypeIterator)
    "generator" -> Ok(RemoteObjectSubtypeGenerator)
    "error" -> Ok(RemoteObjectSubtypeError)
    "proxy" -> Ok(RemoteObjectSubtypeProxy)
    "promise" -> Ok(RemoteObjectSubtypePromise)
    "typedarray" -> Ok(RemoteObjectSubtypeTypedarray)
    "arraybuffer" -> Ok(RemoteObjectSubtypeArraybuffer)
    "dataview" -> Ok(RemoteObjectSubtypeDataview)
    "webassemblymemory" -> Ok(RemoteObjectSubtypeWebassemblymemory)
    "wasmvalue" -> Ok(RemoteObjectSubtypeWasmvalue)
    _ -> Error(chrome.ProtocolError)
  }
}

/// Object property descriptor.
pub type PropertyDescriptor {
  PropertyDescriptor(
    name: String,
    value: option.Option(RemoteObject),
    writable: option.Option(Bool),
    get: option.Option(RemoteObject),
    set: option.Option(RemoteObject),
    configurable: Bool,
    enumerable: Bool,
    was_thrown: option.Option(Bool),
    is_own: option.Option(Bool),
    symbol: option.Option(RemoteObject),
  )
}

/// Object internal property descriptor. This property isn't normally visible in JavaScript code.
pub type InternalPropertyDescriptor {
  InternalPropertyDescriptor(name: String, value: option.Option(RemoteObject))
}

/// Represents function call argument. Either remote object id `objectId`, primitive `value`,
/// unserializable primitive value or neither of (for undefined) them should be specified.
pub type CallArgument {
  CallArgument(
    value: option.Option(dynamic.Dynamic),
    unserializable_value: option.Option(UnserializableValue),
    object_id: option.Option(RemoteObjectId),
  )
}

/// Id of an execution context.
pub type ExecutionContextId {
  ExecutionContextId(Int)
}

/// Description of an isolated world.
pub type ExecutionContextDescription {
  ExecutionContextDescription(
    id: ExecutionContextId,
    origin: String,
    name: String,
    aux_data: option.Option(dict.Dict(String, String)),
  )
}

/// Detailed information about exception (or error) that was thrown during script compilation or
/// execution.
pub type ExceptionDetails {
  ExceptionDetails(
    exception_id: Int,
    text: String,
    line_number: Int,
    column_number: Int,
    script_id: option.Option(ScriptId),
    url: option.Option(String),
    stack_trace: option.Option(StackTrace),
    exception: option.Option(RemoteObject),
    execution_context_id: option.Option(ExecutionContextId),
  )
}

/// Number of milliseconds since epoch.
pub type Timestamp {
  Timestamp(Float)
}

/// Number of milliseconds.
pub type TimeDelta {
  TimeDelta(Float)
}

/// Stack entry for runtime errors and assertions.
pub type CallFrame {
  CallFrame(
    function_name: String,
    script_id: ScriptId,
    url: String,
    line_number: Int,
    column_number: Int,
  )
}

/// Call frames for assertions or error messages.
pub type StackTrace {
  StackTrace(
    description: option.Option(String),
    call_frames: List(CallFrame),
    parent: option.Option(StackTrace),
  )
}
